version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-11-20T22-40-07Z
    restart: always
    command: server --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?err}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?err}
      MINIO_VOLUMES: "/mnt/data"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5